# Generated by Django 6.0.6 on 2026-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0002_refeicao_delete_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='favorita',
            field=models.BooleanField(default=False),
        ),
    ]
